// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnH7HDzAmvf5DKV1WpNC7YqiVn1UG5H8U',
    appId: '1:75412577072:android:4ac948cde82c1a8e0006f5',
    messagingSenderId: '75412577072',
    projectId: 'wiwifit-9cd38',
    storageBucket: 'wiwifit-9cd38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJEasyurJtLxC3qJ-kzGf3CaQDibk-o6U',
    appId: '1:75412577072:ios:1e975f1db42f67eb0006f5',
    messagingSenderId: '75412577072',
    projectId: 'wiwifit-9cd38',
    storageBucket: 'wiwifit-9cd38.appspot.com',
    androidClientId: '75412577072-iki2hkb4t3ce6vo0iqhc983tu8v70o00.apps.googleusercontent.com',
    iosClientId: '75412577072-o3fdbnqvjj2ugs09j79uoi1htm259vb7.apps.googleusercontent.com',
    iosBundleId: 'crossfit.personaltrainer.gymtrainer.fitness',
  );
}
